#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=GiulioManifold
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A_%x.out

module purge
module load 2021
module load Anaconda3/2021.05

# change to code location
cd $HOME/dl1-labs/assignment3/

# Activate your environment
source activate dl1
# Run your code
srun python -u train_pl.py --data_dir $TMPDIR/ --z_dim=2
